name: Testing Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  test-data-db:

    runs-on: ubuntu-latest

    services:

      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: data_user
          POSTGRES_PASSWORD: data_password
        ports:
        - 5432:5432
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup databases
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: data_user
          POSTGRES_PASSWORD: data_password
          DATA_DB_NAME: data
          USER_DB_NAME: users
        run: | 
          chmod +x setup_databases.py
          python setup_databases.py

      - name: Run tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: data_user
          POSTGRES_PASSWORD: data_password
          DATA_DB_NAME: data
          USER_DB_NAME: users
        run: PYTHONPATH=$(pwd) pytest -m "data_db"

      - name: Run user creation tests
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_USER: data_user
          POSTGRES_PASSWORD: data_password
          DATA_DB_NAME: data
          USER_DB_NAME: users
        run: PYTHONPATH=$(pwd) pytest -m "user_creation"